name: Docker Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:0.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK
        run: |
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-apk
          path: ./bin/*.apk
