name: Docker Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .  # 你的项目根目录
          buildozer_version: stable
          command: android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-apk
          path: ./bin/*.apk
